### ISSUE TITLE
android8.1 启动时ComplexIntent 事件丢失，如图，我的小米Android12不会，测了一下模拟器Android9也会丢失

### ISSUE THREAD

**Issue by FanDuiWuXiaoJiaBan** [KunMinX/MVI-Dispatcher#4]
![QQ截图20221029112306](https://user-images.githubusercontent.com/28820373/198803573-5c974ab4-914d-4b30-8290-df6cd4c0184d.png)

**Comment by KunMinX** [comment]
我这边使用 魅族MX6 7.1.2 系统和三星 s8plus 9.0 系统未能复现。
模拟器可能存在不可预期的问题，建议是以真机测试为准。
如果真机也存在丢失结果情况，建议在框架源码中设置更细的 log 来检测，如有结论欢迎补充。

**Comment by FanDuiWuXiaoJiaBan** [comment]
定义了一个参数计数试了一下，事件确实没有丢失，应该是Log的问题导致没有打印出来。我的真机应该是原生Android （定制机），所以表现和模拟器一致
