### ISSUE TITLE
livedate

### ISSUE THREAD

**Issue by xiaxinqing** [KunMinX/MVI-Dispatcher#6]
项目中没有使用到databinding，请问页面状态state如何优雅的替换成 livedate。
旧项目比较庞大，替换datebinding 比较耗时，因此求教。

**Comment by xiaxinqing** [comment]
或者说 不使用databinding的话 就不需要 StateHolder ？也不用StateHolder中State？

**Comment by KunMinX** [comment]
StateHolder 提供旋屏等环境变化时，恢复状态的能力，
如果不使用 databinding，可以考虑 viewBinding，

如果不需要恢复能力，那么直接在 dispatcher 的 output 回调中接收数据即可，
如果需要恢复能力，那么在 StateHolder 中定义唯一的 liveData 对象，然后在 dispatcher 的 output 中 setValue，并在 liveData 的 Observe 中响应各种 binding.view.setxxx，

**Comment by xiaxinqing** [comment]
茅塞顿开，感谢指点
