### ISSUE TITLE
MVI-Dispatcher项目代码是否跟MVI-Dispatcher-KTX的混了

### ISSUE THREAD

**Issue by gdhy-xh** [KunMinX/MVI-Dispatcher#7]
1、项目下载后，编译完成，无法找到 domain 包下的 _Messages 引用，在代码中是 ktx的引用

**Comment by KunMinX** [comment]
没懂你的使用方式哈，猜测你是在同一项目中引入了两个框架。
同一项目中建议只引入其中一个。
java 版下使用了笔者自制的 sealed class 框架，这在 kotlin 下是不必要的。

**Comment by gdhy-xh** [comment]
> 没懂你的使用方式哈，猜测你是在同一项目中引入了两个框架。 同一项目中建议只引入其中一个。 java 版下使用了笔者自制的 sealed class 框架，这在 kotlin 下是不必要的。

下载的 MVI-Dispatcher 代码，跑不起来，其中_Messages 引用都报错了。
