### ISSUE TITLE
Lifecycle库版本报错提示

### ISSUE THREAD

**Issue by qwer2y** [KunMinX/MVI-Dispatcher#8]
继承自MviDispatcher的类IDE会提示错误
Cannot access 'androidx.lifecycle.FullLifecycleObserver' which is a supertype of 'com.xx.zz.event.messenger.BlockMessenger'. Check your module classpath for missing or conflicting dependencies
看起来好像是Lifecycle版本冲突，但是不影响编译和运行。所有使用的地方都有红线提示，看起来有点难受。
现在项目用的Lifecycle版本是2.7.0，能否升级一下依赖库版本？

![img_v3_027m_5c2f2e91-5cf1-4ffa-8aa5-4507878595eg](https://github.com/KunMinX/MVI-Dispatcher/assets/25814380/e9b00653-cefb-4359-9611-aad9490db9a9)
![image](https://github.com/KunMinX/MVI-Dispatcher/assets/25814380/fad94ea8-310c-45fe-9b46-f92c323f5874)

**Comment by KunMinX** [comment]
kotlin 建议是使用 Dispatcher 的 KTX 版。
